sync_bidirectional:
  image: alpine:latest
  before_script:
    - apk add git
  script:
    - GITHUB_URL="https://x-access-token:${GITHUB_TOKEN}@github.com/MarkYQJ/my_test.git"
    - GITLAB_URL="http://cj_lee:${GITLAB_TOKEN}@10.78.26.44:30000/cj_team_test/my_test.git"
    - git init --bare temp_repo
    - cd temp_repo
    - git remote add github $GITHUB_URL
    - git remote add gitlab $GITLAB_URL
    - git fetch github '+refs/*:refs/*'
    - git fetch gitlab '+refs/*:refs/*'
    - git push --mirror github
    - git push --mirror gitlab
  only:
    - schedules
  tags:
    - cloudinfra-setup-global-arm
